[2025-02-05 00:38:40] [INFO    ] discord.client: logging in using static token
[2025-02-05 00:38:41] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a67dd93ee7d7920edd0c163c85713929).
[2025-02-05 00:41:05] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/mnt/2tbdrive/projects/RoyBot/venv/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/mnt/2tbdrive/projects/RoyBot/src/main.py", line 59, in on_message
    await messages.handle_message(client, message)
  File "/mnt/2tbdrive/projects/RoyBot/src/handlers/messages.py", line 77, in handle_message
    data = requests.get(results["results"][0]["media_formats"]["mediumgif"]["url"]).content
                        ~~~~~~~^^^^^^^^^^^
KeyError: 'results'
[2025-02-05 01:26:12] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session a67dd93ee7d7920edd0c163c85713929.
[2025-02-05 04:54:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session a67dd93ee7d7920edd0c163c85713929.
